// @ts-nocheck
/** Sauce Model
 * 
 * Generated by using a mongoose schema
 * 
 * keys required to create a sauce object:
 *  @constructor
    *   @key {string} userId
        @key {string} name
        @key {string }manufacturer 
        @key {string} description
        @key {string} mainPepper
        @key {string} imageUrl
        @key {number} heat 
        @key {number} likes 
        @key {number} dislikes
        @key {array of string} usersLiked
        @key {array of string} usersDisliked
*
* mongoose-sanitize is used to protect from injections and ensure users input allowed html
*
 */

const mongoose = require('mongoose');
const sanitizer = require('mongoose-sanitize');

const sauceSchema = mongoose.Schema({
    userId: { type: String, required: true },
    name: { type: String, required: true },
    manufacturer: { type: String, required: true},
    description: { type: String, required: true },
    mainPepper: { type: String, required: true },
    imageUrl: { type: String, required: true },
    heat: { type: Number, required: true },
    likes: { type: Number, default: 0 },
    dislikes: { type: Number, default: 0 },
    usersLiked: { type:[String], default: [] },
    usersDisliked: { type:[String], default: [] }
});

sauceSchema.plugin(sanitizer);

module.exports = mongoose.model( 'Sauce', sauceSchema);