/** Sauce Model
 * 
 * Generated by using a mongoose schema
 * 
 * keys required to create a sauce object:
 *  @constructor
    *   @key {string} userId
        @key {string} name
        @key {string }manufacturer 
        @key {string} description
        @key {string} mainPepper
        @key {string} imageUrl
        @key {number} heat 
        @key {number} likes 
        @key {number} dislikes
        @key {[string]} usersLiked
        @key {[string]} usersDisliked
 */

const mongoose = require('mongoose');

const sauceSchema = mongoose.Schema({
    userId: { type: String, required: true },
    name: { type: String, required: true },
    manufacturer: { type: String, required: true},
    description: { type: String, required: true },
    mainPepper: { type: String, required: true },
    imageUrl: { type: String, required: true },
    heat: { type: Number, required: true },
    likes: { type: Number, required: true },
    dislikes: { type: Number, required: true },
    usersLiked: { type: [String], required: true },
    usersDisliked: { type: [String], required: true }
});

module.exports = mongoose.model( 'Sauce', sauceSchema);