// @ts-nocheck
/** 
 * User Model
 * Generated by using a mongoose Schema
 * two keys required: 
 * @constructor userSchema
    * @key {string} email  
    * @key {string} password - unique - password is validated by passwordVerify (middleware).
 * 
 * Mongoose unique validator is used to ensure the same email cannot be used twice or more to create different user accounts.
 * 
 */

const mongoose = require('mongoose');
const sanitizer = require('mongoose-sanitize');
const uniqueValidator = require('mongoose-unique-validator');

const userSchema = mongoose.Schema({
    email: { type: String, required: true, unique: true },
    password: { type: String, required: true }
});

userSchema.plugin(uniqueValidator);
userSchema.plugin(sanitizer);

module.exports = mongoose.model('User', userSchema);