/** User Model
 * Generated by using a mongoose Schema
 * two keys required: 
 * @constructor
    * @key {string} email - must match mongoo.SchemaTypes.Email to be valid using npm package mongoose-type-email
    * @key {string} password - unique - password is validated by passwordValidator (password.js)
 * 
 * Mongoose unique validator is used to ensure the same email cannot be used twice or more to create different user accounts
 * 
 */

const mongoose = require('mongoose');
require('mongoose-type-email');
const sanitizer = require('mongoose-sanitize');
const uniqueValidator = require('mongoose-unique-validator');

const userSchema = mongoose.Schema({
    email: { type: mongoose.SchemaTypes.Email, required: true, unique: true },
    password: { type: String, required: true }
});

userSchema.plugin(uniqueValidator);
userSchema.plugin(sanitizer);

module.exports = mongoose.model('User', userSchema);